train:
  output_dir: output
  experiment_name: base
  mode: train
  gui_ip: 127.0.0.1
  gui_port: 6009
  testing_steps:
  - 30000
  saving_ckpt_steps:
  - 30000
  training_steps: 30000
  ckpt: null 
  dataset: 'data/DeepBlending/*'
  resume: true
  save_ply_ascii: true

data:
  path: null
  resolution: -1
  split: 'nan' # 'train', 'test', 'all', 'nan'
  shuffle: true
  white_background: false

model:
  model_name: voxelGS
  lambda_dssim: 0.2
  scaling_reg: 0
  debug: false
  gui_flash_rate: 10
  num_cameras: 300
  rate_proxy:
    lamda: 0.0001
    update_from: 15000
    update_interval: 10
    geometry_rate: 14
  densify:
    start_stat: 500
    update_from: 1500
    update_interval: 100
    update_until: 15000
    min_opacity: 0.005
    success_threshold: 0.8
    densify_grad_threshold: 0.0002
  gaussian:
    feat_dim: 50
    n_offsets: 10
    voxel_size: 0.005
    update_depth: 3
    update_init_factor: 4
    update_hierachy_factor: 4
    use_feat_bank: false
    appearance_dim: 0
    ratio: 1
    add_opacity_dist: false
    add_cov_dist: false
    add_color_dist: false
    qs_inv:
      anchor: 200
      offset: 1
      anchor_feat: 1
      scaling: 8
      rotation: 1
      opacity: 1
  optimize:
    position_lr_init: 0.0
    position_lr_final: 0.0
    position_lr_delay_mult: 0.01
    position_lr_max_steps: 30000
    offset_lr_init: 0.01
    offset_lr_final: 0.0001
    offset_lr_delay_mult: 0.01
    offset_lr_max_steps: 30000
    feature_lr_init: 0.0075  
    feature_lr_final: 0.0075
    feature_lr_delay_mult: 0.01
    feature_lr_max_steps: 30000
    opacity_lr_init: 0.02 
    opacity_lr_final: 0.02
    opacity_lr_delay_mult: 0.01
    opacity_lr_max_steps: 30000
    scaling_lr_init: 0.007
    scaling_lr_final: 0.007
    scaling_lr_delay_mult: 0.01
    scaling_lr_max_steps: 30000
    rotation_lr_init: 0.002  
    rotation_lr_final: 0.002
    rotation_lr_delay_mult: 0.01
    rotation_lr_max_steps: 30000
    mlp_opacity_lr_init: 0.002
    mlp_opacity_lr_final: 2.0e-05
    mlp_opacity_lr_delay_mult: 0.01
    mlp_opacity_lr_max_steps: 30000
    mlp_cov_lr_init: 0.004
    mlp_cov_lr_final: 0.004
    mlp_cov_lr_delay_mult: 0.01
    mlp_cov_lr_max_steps: 30000
    mlp_color_lr_init: 0.008
    mlp_color_lr_final: 5.0e-05
    mlp_color_lr_delay_mult: 0.01
    mlp_color_lr_max_steps: 30000
    mlp_featurebank_lr_init: 0.01
    mlp_featurebank_lr_final: 1.0e-05
    mlp_featurebank_lr_delay_mult: 0.01
    mlp_featurebank_lr_max_steps: 30000
    appearance_lr_init: 0.05
    appearance_lr_final: 0.0005
    appearance_lr_delay_mult: 0.01
    appearance_lr_max_steps: 30000
    percent_dense: 0.01
    
  render:
    compute_cov3D_python: false
    convert_SHs_python: false
    debug_from: -1
    debug: false


